config/routes.rb
ActionController::Routing::Routes.draw do |map|

  match 'ingredients/search' => "ingredients#search", :via => :get, :as => 'ingredient_search'
  match 'ingredients/catalog' => "ingredients#catalog", :via => :get, :as => 'ingredient_catalog'
  match 'ingredients/select' => "ingredients#select", :via => :get, :as => 'ingredient_select'
  match 'recipes/import' => "recipes#import", :via => :get, :as => 'recipe_import'
  match 'recipes/upload' => "recipes#upload", :via => :get, :as => 'recipe_upload'
  match 'warehouses/recalculate' => "warehouses#recalculate", :via => :get, :as => 'recalculate_warehouses'
  match 'transactions/reprocess' => "transactions#reprocess", :via => :get, :as => 'reprocess_transactions'
  match 'roles/:id/clone' => "roles#clone", :via => :get, :as => 'clone_role'
  match 'sessions/not_implemented' => "sessions#not_implemented", :via => :get, :as => "not_implemented"
  # Reports
  match 'reports/index' => "reports#index", :via => :get, :as => "reports"
  match 'reports/recipes' => "reports#recipes", :via => :get, :as => "recipes_report"
  match 'reports/daily_production' => "reports#daily_production", :via => :get, :as => "daily_production_report"
  match 'reports/order_duration' => "reports#order_duration", :via => :get, :as => "order_duration_report"
  match 'reports/order_details' => "reports#order_details", :via => :get, :as => "order_details_report"
  match 'reports/batch_details' => "reports#batch_details", :via => :get, :as => "batch_details_report"
  match 'reports/consumption_per_recipe' => "reports#consumption_per_recipe", :via => :get, :as => "consumption_per_recipe_report"
  match 'reports/consumption_per_ingredients' => "reports#consumption_per_ingredients", :via => :get, :as => "consumption_per_ingredients_report"
  match 'reports/consumption_per_client' => "reports#consumption_per_client", :via => :get, :as => "consumption_per_client_report"
  match 'reports/stock_adjustments' => "reports#stock_adjustments", :via => :get, :as => "stock_adjustments_report"
  match 'reports/lots_incomes' => "reports#lots_incomes", :via => :get, :as => "lots_incomes_report"
  match 'reports/ingredients_stock' => "reports#ingredients_stock", :via => :get, :as => "ingredients_stock_report"
  match 'reports/products_stock' => "reports#products_stock", :via => :get, :as => "products_stock_report"
  match 'reports/product_lots_dispatches' => "reports#product_lots_dispatches", :via => :get, :as => "product_lots_dispatches_report"
  match 'reports/production_per_recipe' => "reports#production_per_recipe", :via => :get, :as => "production_per_recipe_report"
  match 'reports/production_per_client' => "reports#production_per_client", :via => :get, :as => "production_per_client_report"
  match 'batches/:batch_id/batches_hopper_lot' => "batches_hopper_lot#create", :via => :post, :as => "batches_hopper_lot"
  match 'batches/:batch_id/batches_hopper_lot/:id' => "batches_hopper_lot#destroy", :via => :delete, :as => "batch_hopper_lot"
  resources :sessions, :users, :ingredients, :clients, :hoppers, :products, :orders, :lots, :schedules, :batches,
    :transaction_types, :product_lots, :warehouses, :permissions
  resources :transactions, :except=>:edit

  resources :recipes do
    resources :ingredients_recipes
  end

  resources :roles do
    resources :permissions_roles
  end

  root :to => "sessions#index"
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/product_lot.rb
class ProductLot < ActiveRecord::Base
  belongs_to :product
  has_many :order

  validates_uniqueness_of :code
  validates_presence_of :date, :product_id
  validates_length_of :code, :within => 3..20

  def to_collection_select
    "#{self.product.name} (L: #{self.code})"
  end
end

app/controllers/product_lots_controller.rb
class ProductLotsController < ApplicationController
  def index
    @lots = ProductLot.paginate :all, :page=>params[:page], :per_page=>session[:per_page]
  end

  def new
    @products = Product.find :all, :order => 'code ASC'
  end

  def edit
    @lot = ProductLot.find params[:id]
    @products = Product.find :all, :order => 'code ASC'
  end

  def create
    @lot = ProductLot.new params[:lot]
    if @lot.save
      flash[:notice] = 'ProductLot. guardado con éxito'
      redirect_to :product_lots
    else
      new
      render :new
    end
  end

  def update
    @lot = ProductLot.find params[:id]
    @lot.update_attributes(params[:lot])
    if @lot.save
      flash[:notice] = 'Lote guardado con éxito'
      redirect_to :product_lots
    else
      render :edit
    end
  end

  def destroy
    @lot = ProductLot.find params[:id]
    @lot.eliminate
    if @lot.errors.size.zero?
      flash[:notice] = "Lote eliminado con éxito"
    else
      logger.error("Error eliminando lote: #{@lot.errors.inspect}")
      flash[:type] = 'error'
      if not @lot.errors[:foreign_key].nil?
        flash[:notice] = 'El lote no se puede eliminar porque tiene registros asociados'
      elsif not @lot.errors[:unknown].nil?
        flash[:notice] = @lot.errors[:unknown]
      else
        flash[:notice] = "El lote no se ha podido eliminar"
      end
    end
    redirect_to :product_lots
  end
end

app/helpers/product_lots_helper.rb
module ProductLotsHelper
end

app/views/product_lots/_form.html.erb
<%= render_error_messages(f.error_messages) %>
<label for="code" class="small">Código:</label>
<div class="field"><%= f.text_field :code, :size=>'15' %> <span>*</span></div>
<label for="date" class="small">Fecha:</label>
<div class="field"><%= f.date_select :date, :size=>'10' %> <span>*</span></div>
<label for="product_id" class="small">Producto:</label>
<div class="field"><%= f.collection_select :product_id, @products, :id, :name, {:include_blank => true}, :class=>'chzn-select chzn-field-normal' %> <span>*</span></div>
<div class="clearfix"></div>
<br/><span class="required">* Campos obligatorios</span>

app/views/product_lots/edit.html.erb
<%= form_for :lot, :url=>product_lot_path(@lot), :html => {:method=>:put, :id => 'product_lot_edit_form'} do |f| %>
  <%= render :partial=>'form', :locals =>{:f => f} %>
  <br/>
<% end %>

app/views/product_lots/index.html.erb
<% i = 0 %>
<% if @lots.length > 0 %>
<table id="tabledata">
    <thead>
      <tr>
        <th>Código<span class="order_arrow"></span></th>
        <th>Fecha<span class="order_arrow"></span></th>
        <th>Producto<span class="order_arrow"></span></th>
        <th class="actions_small">Acciones</th>
      </tr>
    </thead>
    <tbody>
    <% @lots.each do |item| %>
      <% class_row, i = alternate_row_class(i) %>
      <tr class="<%= class_row %>">
        <td class="center"><%=h item.code %></td>
        <td><%=h item.date %></td>
        <td><%=h item.product.name %></td>
        <td class="center">
          <%= render_action_edit(edit_product_lot_path(item)) %>
          <%= render_action_delete(product_lot_path(item), "Desea borrar el lote '#{item.code}'?") %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>
<div id="tablefooter">
  <div id="pagination">
    <%=raw show_pagination @lots %>
  </div>
</div>
<% else %>
<p>No hay lotes registrados</p>
<% end %>

app/views/product_lots/new.html.erb
<%= form_for :lot, :url=>product_lots_path, :html => {:id => 'product_lot_new_form'} do |f| %>
  <%= render :partial=>'form', :locals =>{:f => f} %>
  <br/>
<% end %>