config/routes.rb
ActionController::Routing::Routes.draw do |map|

  match 'ingredients/search' => "ingredients#search", :via => :get, :as => 'ingredient_search'
  match 'ingredients/catalog' => "ingredients#catalog", :via => :get, :as => 'ingredient_catalog'
  match 'ingredients/select' => "ingredients#select", :via => :get, :as => 'ingredient_select'
  match 'recipes/import' => "recipes#import", :via => :get, :as => 'recipe_import'
  match 'recipes/upload' => "recipes#upload", :via => :get, :as => 'recipe_upload'
  match 'warehouses/recalculate' => "warehouses#recalculate", :via => :get, :as => 'recalculate_warehouses'
  match 'transactions/reprocess' => "transactions#reprocess", :via => :get, :as => 'reprocess_transactions'
  match 'roles/:id/clone' => "roles#clone", :via => :get, :as => 'clone_role'
  match 'sessions/not_implemented' => "sessions#not_implemented", :via => :get, :as => "not_implemented"
  # Reports
  match 'reports/index' => "reports#index", :via => :get, :as => "reports"
  match 'reports/recipes' => "reports#recipes", :via => :get, :as => "recipes_report"
  match 'reports/daily_production' => "reports#daily_production", :via => :get, :as => "daily_production_report"
  match 'reports/order_duration' => "reports#order_duration", :via => :get, :as => "order_duration_report"
  match 'reports/order_details' => "reports#order_details", :via => :get, :as => "order_details_report"
  match 'reports/batch_details' => "reports#batch_details", :via => :get, :as => "batch_details_report"
  match 'reports/consumption_per_recipe' => "reports#consumption_per_recipe", :via => :get, :as => "consumption_per_recipe_report"
  match 'reports/consumption_per_ingredients' => "reports#consumption_per_ingredients", :via => :get, :as => "consumption_per_ingredients_report"
  match 'reports/consumption_per_client' => "reports#consumption_per_client", :via => :get, :as => "consumption_per_client_report"
  match 'reports/stock_adjustments' => "reports#stock_adjustments", :via => :get, :as => "stock_adjustments_report"
  match 'reports/lots_incomes' => "reports#lots_incomes", :via => :get, :as => "lots_incomes_report"
  match 'reports/ingredients_stock' => "reports#ingredients_stock", :via => :get, :as => "ingredients_stock_report"
  match 'reports/products_stock' => "reports#products_stock", :via => :get, :as => "products_stock_report"
  match 'reports/product_lots_dispatches' => "reports#product_lots_dispatches", :via => :get, :as => "product_lots_dispatches_report"
  match 'reports/production_per_recipe' => "reports#production_per_recipe", :via => :get, :as => "production_per_recipe_report"
  match 'reports/production_per_client' => "reports#production_per_client", :via => :get, :as => "production_per_client_report"
  match 'batches/:batch_id/batches_hopper_lot' => "batches_hopper_lot#create", :via => :post, :as => "batches_hopper_lot"
  match 'batches/:batch_id/batches_hopper_lot/:id' => "batches_hopper_lot#destroy", :via => :delete, :as => "batch_hopper_lot"
  resources :sessions, :users, :ingredients, :clients, :hoppers, :products, :orders, :lots, :schedules, :batches,
    :transaction_types, :product_lots, :warehouses, :permissions
  resources :transactions, :except=>:edit

  resources :recipes do
    resources :ingredients_recipes
  end

  resources :roles do
    resources :permissions_roles
  end

  root :to => "sessions#index"
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :batch

  validates_uniqueness_of :name
  validates_presence_of :start_hour, :end_hour
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.paginate :all, :page=>params[:page], :per_page=>session[:per_page]
  end

  def edit
    @schedule = Schedule.find params[:id]
  end

  def create
    @schedule = Schedule.new params[:schedule]
    if @schedule.save
      flash[:notice] = 'Turno guardado con éxito'
      redirect_to :schedules
    else
      render :new
    end
  end

  def update
    @schedule = Schedule.find params[:id]
    @schedule.update_attributes(params[:schedule])
    if @schedule.save
      flash[:notice] = 'Turno guardado con éxito'
      redirect_to :schedules
    else
      render :edit
    end
  end
  
  def destroy
    @schedule = Schedule.find params[:id]
    @schedule.eliminate
    if @schedule.errors.size.zero?
      flash[:notice] = "Turno eliminado con éxito"
    else
      logger.error("Error eliminando turno: #{@schedule.errors.inspect}")
      flash[:type] = 'error'
      if not @schedule.errors[:foreign_key].nil?
        flash[:notice] = 'El turno no se puede eliminar porque tiene registros asociados'
      elsif not @schedule.errors[:unknown].nil?
        flash[:notice] = @schedule.errors[:unknown]
      else
        flash[:notice] = "El turno no se ha podido eliminar"
      end
    end
    redirect_to :schedules
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= render_error_messages(f.error_messages) %>
<label for="name" class="small">Nombre:</label>
<div class="field"><%= f.text_field :name, :size=>'20' %> <span>*</span></div>
<label for="name" class="small">Hora inicio:</label>
<div class="field"><%= f.time_select :start_hour %> <span>*</span></div>
<label for="tel1" class="small">Hora fin:</label>
<div class="field"><%= f.time_select :end_hour %> <span>*</span></div>
<div class="clearfix"></div>
<br/><span class="required">* Campos obligatorios</span>

app/views/schedules/edit.html.erb
<%= form_for :schedule, :url=>schedule_path(@schedule), :html=>{:method=>:put, :id=>'schedule_edit_form'} do |f| %>
  <%= render :partial=>'form', :locals =>{:f => f} %>
  <br/>
<% end %>

app/views/schedules/index.html.erb
<% i = 0 %>
<% if @schedules.length > 0 %>
<table id="tabledata">
    <thead>
      <tr>
        <th>Nombre<span class="order_arrow"></th>
        <th>Hora Inicio<span class="order_arrow"></th>
        <th>Hora Fin<span class="order_arrow"></th>
        <th class="actions_small">Acciones</th>
      </tr>
    </thead>
    <tbody>
    <% @schedules.each do |item| %>
      <% class_row, i = alternate_row_class(i) %>
      <tr class="<%= class_row %>">
        <td><%=h item.name %></td>
        <td><%= item.start_hour.strftime('%I:%M') %></td>
        <td><%= item.end_hour.strftime('%I:%M') %></td>
        <td>
          <%= render_action_edit(edit_schedule_path(item)) %>
          <%= render_action_delete(schedule_path(item), "Desea borrar el turno '#{item.name}'?") %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>
<div id="tablefooter">
  <div id="pagination">
    <%=raw show_pagination @schedules %>
  </div>
</div>
<% else %>
<p>No hay turnos registrados</p>
<% end %>

app/views/schedules/new.html.erb
<%= form_for :schedule, :url=>schedules_path, :html=>{:id=>'schedule_new_form'} do |f| %>
  <%= render :partial=>'form', :locals =>{:f => f} %>
  <br/>
<% end %>