config/routes.rb
ActionController::Routing::Routes.draw do |map|

  match 'ingredients/search' => "ingredients#search", :via => :get, :as => 'ingredient_search'
  match 'ingredients/catalog' => "ingredients#catalog", :via => :get, :as => 'ingredient_catalog'
  match 'ingredients/select' => "ingredients#select", :via => :get, :as => 'ingredient_select'
  match 'recipes/import' => "recipes#import", :via => :get, :as => 'recipe_import'
  match 'recipes/upload' => "recipes#upload", :via => :get, :as => 'recipe_upload'
  match 'warehouses/recalculate' => "warehouses#recalculate", :via => :get, :as => 'recalculate_warehouses'
  match 'transactions/reprocess' => "transactions#reprocess", :via => :get, :as => 'reprocess_transactions'
  match 'roles/:id/clone' => "roles#clone", :via => :get, :as => 'clone_role'
  match 'sessions/not_implemented' => "sessions#not_implemented", :via => :get, :as => "not_implemented"
  # Reports
  match 'reports/index' => "reports#index", :via => :get, :as => "reports"
  match 'reports/recipes' => "reports#recipes", :via => :get, :as => "recipes_report"
  match 'reports/daily_production' => "reports#daily_production", :via => :get, :as => "daily_production_report"
  match 'reports/order_duration' => "reports#order_duration", :via => :get, :as => "order_duration_report"
  match 'reports/order_details' => "reports#order_details", :via => :get, :as => "order_details_report"
  match 'reports/batch_details' => "reports#batch_details", :via => :get, :as => "batch_details_report"
  match 'reports/consumption_per_recipe' => "reports#consumption_per_recipe", :via => :get, :as => "consumption_per_recipe_report"
  match 'reports/consumption_per_ingredients' => "reports#consumption_per_ingredients", :via => :get, :as => "consumption_per_ingredients_report"
  match 'reports/consumption_per_client' => "reports#consumption_per_client", :via => :get, :as => "consumption_per_client_report"
  match 'reports/stock_adjustments' => "reports#stock_adjustments", :via => :get, :as => "stock_adjustments_report"
  match 'reports/lots_incomes' => "reports#lots_incomes", :via => :get, :as => "lots_incomes_report"
  match 'reports/ingredients_stock' => "reports#ingredients_stock", :via => :get, :as => "ingredients_stock_report"
  match 'reports/products_stock' => "reports#products_stock", :via => :get, :as => "products_stock_report"
  match 'reports/product_lots_dispatches' => "reports#product_lots_dispatches", :via => :get, :as => "product_lots_dispatches_report"
  match 'reports/production_per_recipe' => "reports#production_per_recipe", :via => :get, :as => "production_per_recipe_report"
  match 'reports/production_per_client' => "reports#production_per_client", :via => :get, :as => "production_per_client_report"
  match 'batches/:batch_id/batches_hopper_lot' => "batches_hopper_lot#create", :via => :post, :as => "batches_hopper_lot"
  match 'batches/:batch_id/batches_hopper_lot/:id' => "batches_hopper_lot#destroy", :via => :delete, :as => "batch_hopper_lot"
  resources :sessions, :users, :ingredients, :clients, :hoppers, :products, :orders, :lots, :schedules, :batches,
    :transaction_types, :product_lots, :warehouses, :permissions
  resources :transactions, :except=>:edit

  resources :recipes do
    resources :ingredients_recipes
  end

  resources :roles do
    resources :permissions_roles
  end

  root :to => "sessions#index"
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :order
  belongs_to :schedule
  belongs_to :user
  has_many :batch_hopper_lot

  validates_uniqueness_of :order_id, :scope => [:number]
  validates_presence_of :order, :schedule, :user, :start_date, :end_date
  validates_numericality_of :number, :only_integer => true, :greater_than_or_equal_to => 0
  validates_associated :order, :schedule, :user

  before_validation :check_associations

  def check_associations
    if order_id.kind_of?(Integer) && !Order.exists?(order_id)
      errors[:order_id] << "doesn't exist"
    end
    if schedule_id.kind_of?(Integer) && !Schedule.exists?(schedule_id)
      errors[:schedule_id] << "doesn't exist"
    end
    if user_id.kind_of?(Integer) && !User.exists?(user_id)
      errors[:user_id] << "doesn't exist"
    end
  end

  def self.get_real_batches(order_id)
    return self.where(:order_id => order_id).count
  end

  def self.get_real_total(order_id)
    total = 0
    batches = self.where(:order_id => order_id)
    batches.each do |b|
      b.batch_hopper_lot.each do |bhl|
        total += bhl.amount
      end
    end
    return total
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  def index
    @batches = Batch.find :all
  end

  def new
    fill
    @batch = Batch.new :user_id => session[:user].id
  end

  def edit
    fill
    @batch = Batch.find params[:id], :include=>{:batch_hopper_lot=>{:hopper_lot=>[{:lot=>:ingredient}, :hopper]}}
  end

  def create
    @batch = Batch.new params[:batch]
    @saved = @batch.save
    if @saved
      flash[:notice] = 'Batch guardado con éxito'
      redirect_to :batches
    else
      fill
      render :new
    end
  end

  def update
    @batch = Batch.find params[:id]
    @batch.update_attributes(params[:batch])
    if @batch.save
      flash[:notice] = 'Batch actualizado con éxito'
      redirect_to :batches
    else
      fill
      render :edit
    end
  end

  def destroy
    @batch = Batch.find params[:id]
    @batch.eliminate
    if @batch.errors.size.zero?
      flash[:notice] = 'Batch eliminado con éxito'
    else
      logger.error("Error eliminando batch: #{@batch.errors.inspect}")
      flash[:type] = 'error'
      if not @batch.errors[:foreign_key].nil?
        flash[:notice] = 'El batch no se puede eliminar porque tiene registros asociados'
      elsif not @batch.errors[:unknown].nil?
        flash[:notice] = @batch.errors[:unknown]
      else
        flash[:notice] = "El batch no se ha podido eliminar"
      end
    end
    redirect_to :batches
  end

  private

  def fill
    @orders = Order.find :all, :conditions => ['completed = ?', false]
    @users = User.find :all, :order => 'name ASC'
    @schedules = Schedule.find :all, :order => 'name ASC'
    @hoppers = Hopper.actives_to_select
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_edit_grid.html.erb
<% i = 0 %>
<div id="batches_hopper_lots_grid">
  <%= form_for :batch_hopper_lot, :url=>batches_hopper_lot_path(batch) do |f| %>
  <table id="tabledata">
    <thead>
      <tr>
        <th>Tolva<span class="order_arrow"></span></th>
        <th>Cantidad<span class="order_arrow"></span></th>
        <th class="actions_medium">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <%= f.select :hopper_lot_id, @hoppers, {:include_blank => true}, :class=>'chzn-select chzn-done chzn-field-normal' %>
        </td>
        <td><%= f.text_field :amount, :size=>10 %></td>
        <td><%= submit_tag 'Agregar' %></td>
      </tr>
      <% @batch.batch_hopper_lot.each do |bh| %>
        <% class_row, i = alternate_row_class(i) %>
          <tr class="<%= class_row %>">
          <td><%=h "Tolva #{bh.hopper_lot.hopper.number} - #{bh.hopper_lot.lot.ingredient.name} - (L: #{bh.hopper_lot.lot.code})" %></td>
          <td><%=h bh.amount %></td>
          <td><%= render_action_delete(batch_hopper_lot_path(@batch, bh), "Desea eliminar el detalle?") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div id="tablefooter">
    <div id="pagination">
      <!--= show_pagination @recipe %-->
    </div>
  </div>
  <% end %>
</div>

app/views/batches/_form.html.erb
<%= render_error_messages(f.error_messages) %>
<label for="number" class="small">Número:</label>
<div class="field"><%= f.text_field :number, :size=>'10' %> <span>*</span></div>
<label for="code" class="small">Orden Prod.:</label>
<div class="field"><%= f.collection_select :order_id, @orders, :id, :code, {:include_blank => true}, :class=>'chzn-select chzn-field-normal' %> <span>*</span></div>
<label for="start_date" class="small">Inicio:</label>
<div class="field"><%= f.datetime_select :start_date, :include_seconds => true, :default=>DateTime.now, :size=>'10' %> <span>*</span></div>
<label for="end_date" class="small">Fin:</label>
<div class="field"><%= f.datetime_select :end_date, :include_seconds => true, :default=>DateTime.now, :size=>'10' %> <span>*</span></div>
<% if session[:user].admin? %>
<label for="user_id" class="small">Usuario:</label>
<div class="field"><%= f.collection_select :user_id, @users, :id, :login, {:include_blank => true}, :class=>'chzn-select chzn-field-normal' %> <span>*</span></div>
<% else %>
<%= f.hidden_field :user_id %>
<% end %>
<label for="schedule_id" class="small">Turno:</label>
<div class="field"><%= f.collection_select :schedule_id, @schedules, :id, :name, {:include_blank => true}, :class=>'chzn-select chzn-field-normal' %> <span>*</span></div>
<div class="clearfix"></div>
<br/><span class="required">* Campos obligatorios</span>

app/views/batches/edit.html.erb
<%= form_for :batch, :url=>batche_path(@batch), :html=>{:method=>:put, :id=>'batch_edit_form'} do |f| %>
  <%= render :partial=>'form', :locals =>{:f => f, :action=>'edit'} %>
  <br/>
<% end %>
<h5>Detalle de batch</h5>
<%= render :partial=>'edit_grid', :locals =>{:batch => @batch} %>

app/views/batches/index.html.erb
<% i = 0 %>
<% if @batches.length > 0 %>
<table id="tabledata">
    <thead>
      <tr>
        <th>Número<span class="order_arrow"></th>
        <th>Orden Prod.<span class="order_arrow"></th>
        <th>Inicio<span class="order_arrow"></th>
        <th>Fin<span class="order_arrow"></th>
        <th>Usuario<span class="order_arrow"></th>
        <th>Turno<span class="order_arrow"></th>
        <th class="actions_small">Acciones</th>
      </tr>
    </thead>
    <tbody>
    <% @batches.each do |item| %>
      <% class_row, i = alternate_row_class(i) %>
      <tr class="<%= class_row %>">
        <td><%=h item.number %></td>
        <td><%=h item.order.code %></td>
        <td><%=h item.start_date.strftime("%d-%m-%Y %H:%M:%S") %></td>
        <td><%=h item.end_date.strftime("%d-%m-%Y %H:%M:%S") %></td>
        <td><%=h item.user.login %></td>
        <td><%=h item.schedule.name %></td>
        <td>
          <%= render_action_edit(edit_batche_path(item)) %>
          <%= render_action_delete(batche_path(item), "Desea borrar el batch '#{item.number}' de la OP '#{item.order.code}'?") %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>
<div id="tablefooter">
  <div id="pagination">
    <!--=raw show_pagination @batches %-->
  </div>
</div>
<% else %>
<p>No hay batches registrados</p>
<% end %>

app/views/batches/new.html.erb
<%= form_for :batch, :url=>batches_path, :html=>{:id=>'batch_new_form'} do |f| %>
  <%= render :partial=>'form', :locals =>{:f => f, :action=>'new'} %>
  <br/>
<% end %>